//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string AddedSuccess {
            get {
                return ResourceManager.GetString("AddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string DeletedSuccess {
            get {
                return ResourceManager.GetString("DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用成功！ 的本地化字符串。
        /// </summary>
        internal static string DisabledSuccess {
            get {
                return ResourceManager.GetString("DisabledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不存在,可以已经被删除! 的本地化字符串。
        /// </summary>
        internal static string DoesNotExistItMayHaveBeenDeleted {
            get {
                return ResourceManager.GetString("DoesNotExistItMayHaveBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string ModifiedSuccess {
            get {
                return ResourceManager.GetString("ModifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空! 的本地化字符串。
        /// </summary>
        internal static string PasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码与原密码不能相同. 的本地化字符串。
        /// </summary>
        internal static string TwoInputPasswordMustBeConsistent {
            get {
                return ResourceManager.GetString("TwoInputPasswordMustBeConsistent", resourceCulture);
            }
        }
    }
}
