//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.1。
// 
namespace JNHT_ProdSys
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class 开目信息文件
    {

        private 开目信息文件文件属性信息 文件属性信息Field;

        private 开目信息文件数据 数据Field;

        /// <remarks/>
        public 开目信息文件文件属性信息 文件属性信息
        {
            get
            {
                return this.文件属性信息Field;
            }
            set
            {
                this.文件属性信息Field = value;
            }
        }

        /// <remarks/>
        public 开目信息文件数据 数据
        {
            get
            {
                return this.数据Field;
            }
            set
            {
                this.数据Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件文件属性信息
    {

        private decimal 版本号Field;

        private string 文件类型Field;

        private string 文档类型Field;

        /// <remarks/>
        public decimal 版本号
        {
            get
            {
                return this.版本号Field;
            }
            set
            {
                this.版本号Field = value;
            }
        }

        /// <remarks/>
        public string 文件类型
        {
            get
            {
                return this.文件类型Field;
            }
            set
            {
                this.文件类型Field = value;
            }
        }

        /// <remarks/>
        public string 文档类型
        {
            get
            {
                return this.文档类型Field;
            }
            set
            {
                this.文档类型Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件数据
    {

        private 开目信息文件数据元素[] 元素Field;

        private 开目信息文件数据下级信息[] 下级信息Field;

        private byte 标识Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("元素")]
        public 开目信息文件数据元素[] 元素
        {
            get
            {
                return this.元素Field;
            }
            set
            {
                this.元素Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("下级信息")]
        public 开目信息文件数据下级信息[] 下级信息
        {
            get
            {
                return this.下级信息Field;
            }
            set
            {
                this.下级信息Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte 标识
        {
            get
            {
                return this.标识Field;
            }
            set
            {
                this.标识Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件数据元素
    {

        private string 标识Field;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 标识
        {
            get
            {
                return this.标识Field;
            }
            set
            {
                this.标识Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件数据下级信息
    {

        private 开目信息文件数据下级信息数据[] 数据Field;

        private string 标识Field;

        private string 卡片名称Field;

        private string 卡片类型Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("数据")]
        public 开目信息文件数据下级信息数据[] 数据
        {
            get
            {
                return this.数据Field;
            }
            set
            {
                this.数据Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 标识
        {
            get
            {
                return this.标识Field;
            }
            set
            {
                this.标识Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 卡片名称
        {
            get
            {
                return this.卡片名称Field;
            }
            set
            {
                this.卡片名称Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 卡片类型
        {
            get
            {
                return this.卡片类型Field;
            }
            set
            {
                this.卡片类型Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件数据下级信息数据
    {

        private 开目信息文件数据下级信息数据元素[] 元素Field;

        private byte 标识Field;

        private byte 前空行数Field;

        private bool 前空行数FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("元素")]
        public 开目信息文件数据下级信息数据元素[] 元素
        {
            get
            {
                return this.元素Field;
            }
            set
            {
                this.元素Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte 标识
        {
            get
            {
                return this.标识Field;
            }
            set
            {
                this.标识Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte 前空行数
        {
            get
            {
                return this.前空行数Field;
            }
            set
            {
                this.前空行数Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool 前空行数Specified
        {
            get
            {
                return this.前空行数FieldSpecified;
            }
            set
            {
                this.前空行数FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class 开目信息文件数据下级信息数据元素
    {

        private string 标识Field;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 标识
        {
            get
            {
                return this.标识Field;
            }
            set
            {
                this.标识Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}