CREATE TABLE [dbo].[sysBillDataRight] (
    [Iden]          INT        NOT NULL,
    [BillTypeId]    INT        NOT NULL,
    [DataRoleId]    INT        NOT NULL,
    [QueryRight]    INT        NOT NULL,
    [UpdateRight]   INT        NOT NULL,
    [DeleteRight]   INT        NOT NULL,
    [AuditRight]    INT        NOT NULL,
    [PrintRight]    INT        NOT NULL,
    [ExtendRight1]  INT        NOT NULL,
    [ExtendRight2]  INT        NOT NULL,
    [ExtendRight3]  INT        NOT NULL,
    [ExtendRight4]  INT        NOT NULL,
    [ExtendRight5]  INT        NOT NULL,
    [ExtendRight6]  INT        NOT NULL,
    [ExtendRight7]  INT        NOT NULL,
    [ExtendRight8]  INT        NOT NULL,
    [ExtendRight9]  INT        NOT NULL,
    [ExtendRight10] INT        NOT NULL,
    [IsActive]      BIT        CONSTRAINT [DF_sysBillDataRight_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedBy]     INT        NULL,
    [CreatedOn]     DATETIME   NULL,
    [ModifiedBy]    INT        NULL,
    [ModifiedOn]    DATETIME   NULL,
    [VersionNumber] ROWVERSION NULL,
    CONSTRAINT [PK_SystemBillDataRight] PRIMARY KEY CLUSTERED ([Iden] ASC),
    CONSTRAINT [FK_SystemBillDataRight_SystemBillType] FOREIGN KEY ([BillTypeId]) REFERENCES [dbo].[sysBillType] ([Iden]),
    CONSTRAINT [FK_SystemBillDataRight_SystemRole] FOREIGN KEY ([DataRoleId]) REFERENCES [dbo].[sysDataRole] ([Iden])
);

