//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myPortal.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myPortal.BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不能解密哈希字符串。 的本地化字符串。
        /// </summary>
        internal static string CannotUnencodeAHashedPassword {
            get {
                return ResourceManager.GetString("CannotUnencodeAHashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码无效，取消更新。 的本地化字符串。
        /// </summary>
        internal static string ChangePasswordCanceledDueToNewPasswordValidationFailure {
            get {
                return ResourceManager.GetString("ChangePasswordCanceledDueToNewPasswordValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户新密码不能为空。 的本地化字符串。
        /// </summary>
        internal static string NewPasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在的用户或用户已被锁定，无法重置密码！ 的本地化字符串。
        /// </summary>
        internal static string NoUserOrLockedUnableToResetThePassword {
            get {
                return ResourceManager.GetString("NoUserOrLockedUnableToResetThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用密码重置功能。 的本地化字符串。
        /// </summary>
        internal static string PasswordResetIsNotEnabled {
            get {
                return ResourceManager.GetString("PasswordResetIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码重置操作已经被取消。 的本地化字符串。
        /// </summary>
        internal static string ResetPasswordOperationHasBeenCancelled {
            get {
                return ResourceManager.GetString("ResetPasswordOperationHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成NewIden时，&quot;sGroupName&quot;不能为空。 的本地化字符串。
        /// </summary>
        internal static string sGroupNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("sGroupNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;sUserNo&quot;不能为空！ 的本地化字符串。
        /// </summary>
        internal static string sUserNoCanNotBeNull {
            get {
                return ResourceManager.GetString("sUserNoCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除用户，无法重置密码。 的本地化字符串。
        /// </summary>
        internal static string TheDeletedUserUnableToResetThePassword {
            get {
                return ResourceManager.GetString("TheDeletedUserUnableToResetThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员资格提供程序无法更新非系统用户信息！ 的本地化字符串。
        /// </summary>
        internal static string TheMembershipProviderIsUnableToUpdateTheSystemUserInformation {
            get {
                return ResourceManager.GetString("TheMembershipProviderIsUnableToUpdateTheSystemUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要更新的saUser不能为空！  的本地化字符串。
        /// </summary>
        internal static string TheUpdatedSaUserCanNotBeNull {
            get {
                return ResourceManager.GetString("TheUpdatedSaUserCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在。 的本地化字符串。
        /// </summary>
        internal static string TheUserDoesNotExist {
            get {
                return ResourceManager.GetString("TheUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的密码加密方式。 的本地化字符串。
        /// </summary>
        internal static string UnsupportedPasswordFormat {
            get {
                return ResourceManager.GetString("UnsupportedPasswordFormat", resourceCulture);
            }
        }
    }
}
